FROM mysql:8.0

# Add your SQL initialization script
ADD ./create_table.sql /docker-entrypoint-initdb.d/1.sql

# Set environment variables for MySQL
ENV MYSQL_USER=h2
ENV MYSQL_USER=h2
ENV MYSQL_PASSWORD=Imaging5-CELL
ENV MYSQL_DATABASE=web_scraping
ENV MYSQL_ROOT_PASSWORD=zinc9-bartholomew-ETHNIC

# Expose port 3306 for MySQL
EXPOSE 3306